coverage:
  status:
    project:
      default:
        target: 100%
  precision: 2
  round: down
  range: "70..100"
  ignore:
    - "tests/*"
    - "vendor/*"
fixes:
  - "/home/runner/work/translation-bundle/translation-bundle/::"