services:
    Umanit\TranslationBundle\Translation\EntityTranslator: '@umanit_translation.translation.entity_translator'

    umanit_translation.translation.entity_translator:
        class: Umanit\TranslationBundle\Translation\EntityTranslator
        arguments:
            - '%umanit_translation.locales%'
            - '@event_dispatcher'
            - '@umanit_translation.utils.annotation_helper'

    umanit_translation.utils.annotation_helper:
        class: Umanit\TranslationBundle\Utils\AnnotationHelper
        arguments: ['@annotations.reader']

    # Translation Handlers

    # Scalar
    umanit_translation.translation.handlers.scalar:
        class: Umanit\TranslationBundle\Translation\Handlers\Scalar
        tags:
            - { name: umanit_translation.translation_handler, priority: 1 }

    # Doctrine Object
    umanit_translation.translation_handlers.doctrine_object:
        class: Umanit\TranslationBundle\Translation\Handlers\DoctrineObject
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@umanit_translation.translation.entity_translator'
        tags:
            - { name: umanit_translation.translation_handler, priority: 100 }

    # Legacy translator
    umanit_translation.translator.entity_translator:
        class: Umanit\TranslationBundle\Translator\EntityTranslator
        arguments: ['%umanit_translation.locales%', '@doctrine.orm.entity_manager', '@annotations.reader', '@event_dispatcher']

    umanit_translation.twig.umanit_translation_extension:
        class: Umanit\TranslationBundle\Twig\UmanitTranslationExtension
        arguments: ['%umanit_translation.locales%']
        tags:
            - { name: twig.extension }

    umanit_translation.doctrine.event_subscriber.translatable_event_subscriber:
        class: Umanit\TranslationBundle\Doctrine\EventSubscriber\TranslatableEventSubscriber
        arguments: ['@annotation_reader', '%kernel.default_locale%']
        tags:
            - { name: doctrine.event_subscriber }

    umanit_translation.event_subscriber.locale_filter_configurator:
        class: Umanit\TranslationBundle\EventSubscriber\LocaleFilterConfigurator
        arguments: ['@doctrine.orm.entity_manager', '%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }